ESSENTIAL="man-db man-pages pacman-contrib"
MICROCODE="intel-ucode amd-ucode"
DEVELOPMENT="base-devel git"
DISKMGM="e2fsprogs dosfstools ntfs-3g"
CONSOLE="vim vim-airline vim-fugitive grml-zsh-config"
MULTIMEDIA="gstreamer alsa-utils mpv"
NETWORKING="networkmanager"
UTILS="xdg-user-dirs unrar p7zip"

RECIPE_PKGS="$ESSENTIAL $MICROCODE $DEVELOPMENT $DISKMGM $CONSOLE $MULTIMEDIA $NETWORKING $UTILS"
